/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.calculator_app;

import java.awt.event.ActionEvent;
import javax.swing.JTextField;
////
/**
 *
 * @author jagmeet
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    public static String answer ="test3";
   public static String answer2 ="notmodified";
    public calculator() {
        initComponents();
        on.setEnabled(false);
    }
    
    double num1=0.0;
    int flag=0;
    char op='+';
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollBar1 = new javax.swing.JScrollBar();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        on = new javax.swing.JRadioButton();
        ac = new javax.swing.JButton();
        negation = new javax.swing.JButton();
        modulas = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        subtraction = new javax.swing.JButton();
        addition = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        off = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        backspace = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyCalculator");
        setBackground(new java.awt.Color(0, 0, 0));

        buttonGroup1.add(on);
        on.setSelected(true);
        on.setText("On");
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });

        ac.setText("AC");
        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });

        negation.setText("+/-");
        negation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negationActionPerformed(evt);
            }
        });

        modulas.setText("%");
        modulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulasActionPerformed(evt);
            }
        });

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        multiply.setText("x");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        subtraction.setText("-");
        subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionActionPerformed(evt);
            }
        });

        addition.setText("+");
        addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionActionPerformed(evt);
            }
        });

        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        buttonGroup1.add(off);
        off.setText("Off");
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        dot.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        dot.setText(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        backspace.setText("<-");
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(addition, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(subtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(off, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(on, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(negation, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(modulas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ac)
                    .addComponent(negation)
                    .addComponent(modulas)
                    .addComponent(off, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(divide)
                            .addComponent(backspace))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(on, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(multiply))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(subtraction))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(jButton9)
                            .addComponent(addition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton0)
                            .addComponent(dot)
                            .addComponent(equal))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void enable() {
        on.setEnabled(false);
        off.setEnabled(true);
        jButton0.setEnabled(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        multiply.setEnabled(true);
        backspace.setEnabled(true);
        negation.setEnabled(true);
        addition.setEnabled(true);
        divide.setEnabled(true);
        subtraction.setEnabled(true);
        modulas.setEnabled(true);
        jTextField1.setEnabled(true);
        jLabel1.setEnabled(true);
        jButton0.setEnabled(true);
        dot.setEnabled(true);
        ac.setEnabled(true);
        equal.setEnabled(true);
        
        
        
        
        
    } 
    @Override
    public void disable() {                                         
       on.setEnabled(true);
        off.setEnabled(false);
        jButton0.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
        multiply.setEnabled(false);
        backspace.setEnabled(false);
        negation.setEnabled(false);
        addition.setEnabled(false);
        divide.setEnabled(false);
        subtraction.setEnabled(false);
        modulas.setEnabled(false);
        jTextField1.setEnabled(false);
        jLabel1.setEnabled(false);
        jButton0.setEnabled(false);
        dot.setEnabled(false);
        ac.setEnabled(false);
        equal.setEnabled(false);
    } 
    String fun (double d1,double d2)
    {
        
        switch(op)
        {
                case '+':
                return (d1+d2)+"";
                //break;
                case '-':
                return (d1-d2)+"";
                //break;
                case '*':
                return (d1*d2)+"";
                //break;
                case '/':
                return (d1/d2)+"";
                //break;
                case '%':
                return (d1%d2)+"";
                //break;
        }
        return ""; 
    }
    public void multiplyActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
    multiplyActionPerformed(evt);
    
}
    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        String str = jTextField1.getText();
        //jTextField1.setText("");
        if(str.length()==0 || (str.length()==1 && str.charAt(0)=='-'))
        {
            //return;
        }
        else
        {
            flag=1;
            op='*';
            if(str.charAt(0)=='-')
            {
               num1 = Double.parseDouble(str.substring(1));
               num1*=-1;
            }
            else
            {
               num1 = Double.parseDouble(str);  
            }
            jTextField1.setText("");
            answer = "";
             jLabel1.setText(num1+"*");
        }
        
    }//GEN-LAST:event_multiplyActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
        enable();
    }//GEN-LAST:event_onActionPerformed

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
        disable();
    }//GEN-LAST:event_offActionPerformed
   public void jButton7ActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
    jButton7ActionPerformed(evt);
    
}
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTextField1.setText(jTextField1.getText()+"7");
        answer = jTextField1.getText()+"7";
    }//GEN-LAST:event_jButton7ActionPerformed
 public void jButton1ActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
    jButton1ActionPerformed(evt);
    
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField1.setText(jTextField1.getText()+"1");
        answer = jTextField1.getText()+"1";
    }//GEN-LAST:event_jButton1ActionPerformed
    public void jButton8ActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
    jButton8ActionPerformed(evt);
    
}
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       jTextField1.setText(jTextField1.getText()+"8");
       answer = jTextField1.getText()+"8";
    }//GEN-LAST:event_jButton8ActionPerformed
    public void jButton9ActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
    jButton9ActionPerformed(evt);
    
}
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jTextField1.setText(jTextField1.getText()+"9");
        answer = jTextField1.getText()+"9";
    }//GEN-LAST:event_jButton9ActionPerformed
    public void jButton6ActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
    jButton6ActionPerformed(evt);
    
}
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextField1.setText(jTextField1.getText()+"6");
        answer = jTextField1.getText();
    }//GEN-LAST:event_jButton6ActionPerformed
    public void jButton5ActionPerformedCall()
    {
        java.awt.event.ActionEvent evt = null;
    jButton5ActionPerformed(evt);
    
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextField1.setText(jTextField1.getText()+"5");
        answer = jTextField1.getText();
    }//GEN-LAST:event_jButton5ActionPerformed
public void jButton4ActionPerformedCall()
    {
        java.awt.event.ActionEvent evt = null;
    jButton4ActionPerformed(evt);
    
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField1.setText(jTextField1.getText()+"4");
        answer = jTextField1.getText();
    }//GEN-LAST:event_jButton4ActionPerformed
public void jButton3ActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
    jButton3ActionPerformed(evt);
    
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jTextField1.setText(jTextField1.getText()+"3");
       //answer = jTextField1.getText()+"3";
       answer = jTextField1.getText();
       answer2+="3";
    }//GEN-LAST:event_jButton3ActionPerformed
public void jButton2ActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
    jButton2ActionPerformed(evt);
    
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText(jTextField1.getText()+"2");
        //answer = jTextField1.getText()+"2";
        answer = jTextField1.getText();
        answer2+="2";
    }//GEN-LAST:event_jButton2ActionPerformed
public void acActionPerformedCall()
    {
        java.awt.event.ActionEvent evt = null;
    acActionPerformed(evt);
    
    }
    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        jTextField1.setText( "");
        jLabel1.setText("");
        flag=0;
       answer = jTextField1.getText();
    }//GEN-LAST:event_acActionPerformed
    public void backspaceActionPerformedCall()
    {
        java.awt.event.ActionEvent evt = null;
    backspaceActionPerformed(evt);
    
    }
    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
         String str = jTextField1.getText();
         if(str.length()>0)
         {
          jTextField1.setText(str.substring(0,str.length()-1));
         answer = jTextField1.getText();  
         }
         
    }//GEN-LAST:event_backspaceActionPerformed
    public void negationActionPerformedCall()
    {
        java.awt.event.ActionEvent evt = null;
    negationActionPerformed(evt);
    
    }
    private void negationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negationActionPerformed
       String str = jTextField1.getText();
       if(str.length()>0 && str.charAt(0)=='-')
           str=str.substring(1);
       else
           str = "-"+str;
       jTextField1.setText(str);
        answer = jTextField1.getText(); 
    }//GEN-LAST:event_negationActionPerformed
    public void jButton0ActionPerformedCall()
    {
        java.awt.event.ActionEvent evt = null;
    jButton0ActionPerformed(evt);
    
    }
    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        jTextField1.setText(jTextField1.getText()+"0");
         answer = jTextField1.getText(); 
    }//GEN-LAST:event_jButton0ActionPerformed
    public void modulasActionPerformedCall()
    {
        java.awt.event.ActionEvent evt = null;
    modulasActionPerformed(evt);
    
    }
    private void modulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulasActionPerformed
          String str = jTextField1.getText();
        //jTextField1.setText("");
        if(str.length()==0 || (str.length()==1 && str.charAt(0)=='-'))
        {
            //return;
        }
        else
        {
            flag=1;
            op='%';
            if(str.charAt(0)=='-')
            {
               num1 = Double.parseDouble(str.substring(1));
               num1*=-1;
            }
            else
            {
               num1 = Double.parseDouble(str);  
            }
            jTextField1.setText("");
            answer = jTextField1.getText();
             jLabel1.setText(num1+"%");
        }
    }//GEN-LAST:event_modulasActionPerformed
public void equalActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
    equalActionPerformed(evt);
    //jTextField1.setText("executed");
    
}
    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        
        String str = jTextField1.getText();
        if(flag==0)
        {
          // return;
             answer2=answer2+"ifs=";
        }
        else
        {
           if(str.length()==0 || (str.length()==1 && str.charAt(0)=='-'))
           {
            // return;  
               answer2=answer2+"if=";
           }
            else
            {
                flag=0;
                double num2;
                if(str.charAt(0)=='-')
                {
                   num2 = Double.parseDouble(str.substring(1)) * -1;
                   
                }
                else
                {
                   num2 = Double.parseDouble(str);  
                }
               jTextField1.setText(fun(num1,num2));
              answer = jTextField1.getText();
              answer2=answer2+"i=";
               //answer="5";
              // answer2 ="modified"; 
               jLabel1.setText("");
            } 
           answer2=answer2+"e=";
        }
        //jTextField1.setText("0");
        // answer = jTextField1.getText();
        answer2=answer2+"o=";
    }//GEN-LAST:event_equalActionPerformed
    public void cal(char c) {
        java.awt.event.ActionEvent evt;
         //calculator instance = new calculator();
        switch(c)
        {
                case '+':
                additionActionPerformedCall();
                break;
                case '-':
                subtractionActionPerformedCall();
                break;
                //break;
                case '*':
                multiplyActionPerformedCall();
                break;
                //break;
                case '/':
                divideActionPerformedCall();
                break;
                //break;
                case '%':
                modulasActionPerformedCall();
                break;
                //break;
                case '=':
                equalActionPerformedCall();
                break;
                case 'b':
                backspaceActionPerformedCall();
                break;
                case 'm':
                negationActionPerformedCall();
                break;
                case 'c':
                acActionPerformedCall();
                break;
                case '1':
                jButton1ActionPerformedCall();
                break;
                case '2':
                jButton2ActionPerformedCall();
                break;
                case '3':
                jButton3ActionPerformedCall();
                break;
                case '4':
                jButton4ActionPerformedCall();
                break;
                case '5':
                jButton5ActionPerformedCall();
                break;
                case '6':
                jButton6ActionPerformedCall();
                break;
                case '7':
                jButton7ActionPerformedCall();
                break;
                case '8':
                jButton8ActionPerformedCall();
                break;
                case '9':
                jButton9ActionPerformedCall();
                break;
                case '0':
                jButton0ActionPerformedCall();
                break;
                case '.':
               dotActionPerformedCall();
                break;
        }
    }
    public void call(String exp)
    {
       for(int i=0;i<exp.length();i++)
        {
          cal(exp.charAt(i));  
        } 
    }
    public void subtractionActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
    subtractionActionPerformed(evt);
    
    
}
    private void subtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionActionPerformed
          String str = jTextField1.getText();
        //jTextField1.setText("");
        if(str.length()==0 || (str.length()==1 && str.charAt(0)=='-'))
        {
            //return;
        }
        else
        {
            flag=1;
            op='-';
            if(str.charAt(0)=='-')
            {
               num1 = Double.parseDouble(str.substring(1));
               num1*=-1;
            }
            else
            {
               num1 = Double.parseDouble(str);  
            }
            jTextField1.setText("");
            answer = jTextField1.getText();
             jLabel1.setText(num1+"-");
        }
    }//GEN-LAST:event_subtractionActionPerformed
    public void divideActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
    divideActionPerformed(evt);
    
    
}
    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
          String str = jTextField1.getText();
        //jTextField1.setText("");
        if(str.length()==0 || (str.length()==1 && str.charAt(0)=='-'))
        {
            //return;
        }
        else
        {
            flag=1;
            op='/';
            if(str.charAt(0)=='-')
            {
               num1 = Double.parseDouble(str.substring(1));
               num1*=-1;
            }
            else
            {
               num1 = Double.parseDouble(str);  
            }
            jTextField1.setText("");
            answer = jTextField1.getText();
             jLabel1.setText(num1+"/");
        }
    }//GEN-LAST:event_divideActionPerformed
public void additionActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
    additionActionPerformed(evt);
    
}
    private void additionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionActionPerformed
          String str = jTextField1.getText();
        //jTextField1.setText("");
        if(str.length()==0 || (str.length()==1 && str.charAt(0)=='-'))
        {
            //return;
        }
        else
        {
            flag=1;
            op='+';
            if(str.charAt(0)=='-')
            {
               num1 = Double.parseDouble(str.substring(1));
               num1*=-1;
            }
            else
            {
               num1 = Double.parseDouble(str);  
            }
            jTextField1.setText("");
            answer = jTextField1.getText();
             jLabel1.setText(num1+"+");
        }
        answer2=answer2+"+";
    }//GEN-LAST:event_additionActionPerformed
public void dotActionPerformedCall()
{
        java.awt.event.ActionEvent evt = null;
   dotActionPerformed(evt);
    
}
    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        String str = jTextField1.getText();
        
        if(str.length()==0)
        {
            jTextField1.setText("0.");
            answer = jTextField1.getText();
        }
        else if(str.length()>0 && str.indexOf('.')>=0)
        {
            //return;
            
        }
            
        else
        {
          jTextField1.setText(str+"."); 
          answer = jTextField1.getText();
        }
        
    }//GEN-LAST:event_dotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }
    
    public String getTextField1()
    {
        return jTextField1.getText();
    }
    public String getAnswer()
    {
        return answer;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ac;
    private javax.swing.JButton addition;
    private javax.swing.JButton backspace;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton divide;
    private javax.swing.JButton dot;
    private javax.swing.JButton equal;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton modulas;
    private javax.swing.JButton multiply;
    private javax.swing.JButton negation;
    private javax.swing.JRadioButton off;
    private javax.swing.JRadioButton on;
    private javax.swing.JButton subtraction;
    // End of variables declaration//GEN-END:variables
}
